name: icecast-arm64v8

on:
  workflow_dispatch:
  push:
    branches:
      - "master"
    paths:
      - "icecast/**"
  schedule:
    - cron: '0 5 * * *'

jobs:
  docker:
    runs-on: self-hosted
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and Push
        uses: docker/build-push-action@v3
        with:
          push: true
          context: "${{ github.server_url }}/${{ github.repository }}.git#${{ github.ref }}:icecast"
          tags: |
            ${{ secrets.DOCKERHUB_SLUG }}/icecast:arm64v8-latest
            ${{ secrets.DOCKERHUB_SLUG }}/icecast:arm64v8-${{github.run_number}}
