name: icecast-amd64

on:
  workflow_dispatch:
  push:
    branches:
      - "master"
    paths:
      - "icecast/**"

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and Push
        uses: docker/build-push-action@v3
        with:
          push: true
          context: "${{ github.server_url }}/${{ github.repository }}.git#${{ github.ref }}:icecast"
          tags: |
            ${{ secrets.DOCKERHUB_SLUG }}/icecast:amd64-latest
            ${{ secrets.DOCKERHUB_SLUG }}/icecast:amd64-${{github.run_number}}
