name: mopidy-arm64v8

on:
  workflow_dispatch:
  push:
    branches:
      - "master"
    paths:
      - "mopidy/**"

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          buildkitd-flags: "--debug"
      - name: Hack docker filesystem to create small tmpfs for docker cache
        run: |
          df -h
          sudo swapon --show
          sudo dd if=/dev/zero of=/swapfile1 bs=1M count=10K 
          sudo chmod 600 /swapfile1
          sudo mkswap /swapfile1
          sudo swapon /swapfile1
          sudo swapon --show
          sudo free -h
          sudo systemctl stop docker
          sudo mount -t tmpfs -o size=15G tmpfs /var/lib/docker
          df -h
          sudo systemctl start docker
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and Push
        uses: docker/build-push-action@v3
        with:
          platforms: linux/arm64
          push: true
          context: "${{ github.server_url }}/${{ github.repository }}.git#${{ github.ref }}:mopidy"
          tags: ${{ secrets.DOCKERHUB_SLUG }}/mopidy:arm64v8-latest
