version: "2.4"

services:
  snapserver:
    container_name: snapserver
    image: rfabri/snapserver:arm64v8-latest
    restart: unless-stopped
    command: snapserver
    ports:
      - "1704:1704"
      - "1705:1705"
      - "1780:1780"
    volumes:
      - ~/snapserver/:/root/.config/snapserver/
      - ~/snapserver/snapserver.conf:/etc/snapserver.conf
      - /tmp:/tmp
      - /var/run/avahi-daemon:/var/run/avahi-daemon
      - /var/run/dbus:/var/run/dbus

  mopidy-snapserver:
    container_name: mopidy-snapserver
    image: rfabri/mopidy:arm64v8-latest
    restart: unless-stopped
    ports:
      - "6600:6600"
      - "6680:6680"
      - "5555:5555/udp"
    depends_on:
      - snapserver
    volumes:
      - ~/mopidy-icesnap/mopidy/mopidy-snapserver.conf:/mopidy/mopidy.conf
      - ~/mopidy-snapserver/:/mopidy
      - /tmp:/tmp

  stream-manager:
    container_name: stream-manager
    image: rfabri/stream-manager:arm64v8-latest
    environment:
      -  SNAPSERVER_IP=<SNAPSERVER_IP>
      -  SNAPSERVER_PORT=<SNAPSERVER_PORT>
    restart: unless-stopped
    depends_on:
      - snapserver